### ISSUE TITLE
Compatibility with Impostor 1.3.0

### ISSUE THREAD

**Issue by WolfwithSword** [dimaguy/ImpostorHQ#18]
Impostor 1.3.0 was recently created, but some changes appear to cause ImpostorHQ to no longer run, so it needs to be updated to be compatible.

The issue arises after loading ImpostorHQ, as it immediately throws a SocketException. I tried changing the ports in the config to others randomly, both for Impostor and ImpostorHQ such that they were different or the same. No other instance was running and those ports were not in use otherwise.

Full error can be seen in the attached image.
Using Impostor v1.3.0-ci.128. This issue was not present in Impostor 1.2.2.

![image](https://user-images.githubusercontent.com/12175651/109815787-6a4cd400-7c06-11eb-9a6e-19af88b0f865.png)

**Comment by dimaguy** [comment]
Thanks for informing me. I found the root of the issue (conflicting announcement servers) and will work in order to solve it

**Comment by dimaguy** [comment]
Status update: I already have a solution in line, in order to keep backwards compatibility, I will create a Legacy Announcement server option, which should remain as false in your case. I am awaiting on the latest nuget package in order to implement Impostor's native announcement server

**Comment by dimaguy** [comment]
Fixed with commit d2db4fb
