### ISSUE TITLE
Colors Broadcast dont work

### ISSUE THREAD

**Issue by InLoveWithLua** [dimaguy/ImpostorHQ#23]
Hey im using latest Version but the Broadcast colors wont work. Its shows like that in Chat: [#F24124]Broudcastmessage. would be nice to use colors in Chat ánd it would be sick if you could add something like: every 10 Minutes automatic Broadcast Message to all Lobbys:D

**Comment by dimaguy** [comment]
Color rendering is up to Among Us game, not ImpostorHQ.
Scheduled message broadcast is too niche of a feature to add to iHQ, so I am not adding it anytime soon. There is a websocket api so you can probably work out something for your case
