### ISSUE TITLE
broadcast color not work

### ISSUE THREAD

**Issue by Hoax017** [dimaguy/ImpostorHQ#28]
Test with : 
/broadcast Black:Hi

![image](https://user-images.githubusercontent.com/8215575/115541871-e7f49e00-a29f-11eb-84e0-43df25b6b375.png)

**Comment by dimaguy** [comment]
1. Check for existing issues before opening a new one (#23 Points to the exact same issue)
2. This is Among Us fault, not impostor's. Innersloth made it stop rendering colors.
