### ISSUE TITLE
Can't access web interface

### ISSUE THREAD

**Issue by netzpixel** [dimaguy/ImpostorHQ#30]
I just installed the plugin but I have no clue what so ever how to access the web interface. I also found no documentation which could help me.

In the logs I found this line:
ImpostorHQ : API Server listening on: 0.0.0.0:22023. Dashboard listening on: 0.0.0.0:22024/client.html

and I tried every possible combination to get to the client.html but no luck. (everything is happening in a local environment, and Impostor is running in a docker container)

What am I doing wrong? 
Could you please write a more helpful documentation?
Thanks in advance!

**Comment by dimaguy** [comment]
Did you expose port 22024/tcp and port 22023/tcp in the docker container?

P.S: Also, yes there are a few issues in this repo I havent had time to fix: the documentation at the moment is a WIP for a complete codebase rehaul that has occured in the last Pull Request,  but the latest release still only reflects the previous codebase which follows some different rules.
You can download the zip folder with the source code in the release files, it contains the previous docs

**Comment by netzpixel** [comment]
Well, I did nothing different on the linux server... so I guess I exposed the ports. But it's working for me now with linux so you can close the ticket if you want to.

**Comment by netzpixel** [comment]
Oh gosh ... I just realized  I mixed this up with a different ticket I opened... But still... opening up the ports in docker did the trick. But still... the page looks a lot different from the demo page. There are no graphs what so ever. Is that supposed to be that way? And also is there a way to put the auth key in the URL so I don't have to put it in the login field every time?

**Comment by dimaguy** [comment]
> 
> 
> Oh gosh ... I just realized I mixed this up with a different ticket I opened... But still... opening up the ports in docker did the trick. But still... the page looks a lot different from the demo page. There are no graphs what so ever. Is that supposed to be that way? And also is there a way to put the auth key in the URL so I don't have to put it in the login field every time?

Could you provide me with a screencap? Are you using the release or the compiled source

**Comment by netzpixel** [comment]
I used brave browser which somehow "blocked" the files... in every other browser it works. It's just strange, that the demo site works just normal... 
I used the release version.

But still, is there a way to put the auth key in the url?

**Comment by dimaguy** [comment]
"?apikey=(apikey)" At the end of your url.
If I had to guess, brave browser has stricter policies for localhost than for websites with domain
